# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_SEC_BSP) += sec_bsp.o sec_smem.o
obj-$(CONFIG_SEC_AP_HEALTH) += sec_hw_param.o
obj-$(CONFIG_SEC_DEBUG) += sec_debug.o sec_gaf.o sec_getlog.o sec_key_notifier.o
obj-$(CONFIG_SEC_DEBUG_DOUBLE_FREE) += sec_debug-dfd.o
obj-$(CONFIG_SEC_DEBUG_SUMMARY) += sec_debug_summary.o
obj-$(CONFIG_SEC_MONITOR_BATTERY_REMOVAL) += sec_monitor_battery_removal.o
# Samsung sec NAD Feature
obj-$(CONFIG_SEC_NAD)		+= sec_nad.o
