#
# Makefile for the Zinitix Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT532)	+= zinitix_bt532_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT431)	+= zinitix_bt532_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX)	+= zinitix_bt532_ts.o