# Exynos DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS_DEVFREQ)	+= exynos-devfreq.o
obj-$(CONFIG_ARM_EXYNOS8890_BUS_DEVFREQ)+= exynos8890_bus_mif.o exynos8890_bus_int.o exynos8890_bus_disp.o exynos8890_bus_cam.o
obj-$(CONFIG_ARM_EXYNOS8895_BUS_DEVFREQ)+= exynos8895_bus_mif.o exynos8895_bus_int.o exynos8895_bus_disp.o exynos8895_bus_cam.o exynos8895_bus_intcam.o
obj-$(CONFIG_ARM_EXYNOS9810_BUS_DEVFREQ)+= exynos9810_bus_mif.o exynos9810_bus_int.o exynos9810_bus_disp.o exynos9810_bus_cam.o exynos9810_bus_intcam.o exynos9810_bus_aud.o exynos9810_bus_iva.o exynos9810_bus_score.o exynos9810_bus_fsys0.o
obj-$(CONFIG_EXYNOS_WD_DVFS)	+= exynos_ppmu.o
