#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_EXYNOS_MIPI_DSIM) += panel.o panel_bl.o dimming.o panel_drv.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HF3) += s6e3hf3/s6e3hf3.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA2) += s6e3ha2/s6e3ha2.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HF4) += s6e3hf4/s6e3hf4.o

obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS) += sysfs.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
