#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_EXYNOS_MIPI_DSIM) += panel.o panel_bl.o dimming.o panel_drv.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HF4) += s6e3hf4/s6e3hf4.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA6) += s6e3ha6/s6e3ha6.o
obj-$(CONFIG_EXYNOS_DECON_LCD_TUNING) += tuning.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS) += sysfs.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SPI) += spi.o
obj-$(CONFIG_EXYNOS_DECON_LCD_COPR) += copr.o
obj-$(CONFIG_ACTIVE_CLOCK) += active_clock.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
obj-$(CONFIG_SUPPORT_POC_FLASH) += panel_poc.o
