#
# Exynos HDCP drivers
#

# HDCP
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-tx-auth.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-tx-session.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-teeif.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-protocol-msg.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-selftest.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-misc.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-encrypt.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-crypto.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-if.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-auth.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-protocol-msg.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-selftest.o
