#
# Makefile for the vibrator driver ICs with vibrator driver
#
obj-$(CONFIG_MSM_VIBRATOR) += msm_vibrator.o
# Makefile for Vibrator controlled by SUB PMIC Regulator.
obj-$(CONFIG_SM5703_VIBRATOR) += sm5703_vibrator.o

