#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_DRV_MAX77854)	+= max77854_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77865)	+= max77865_haptic.o
obj-$(CONFIG_MOTOR_DRV2624)		+= drv2624.o
