obj-$(CONFIG_EXYNOS_IVA) := iva_ctl.o

EXTRA_CFLAGS += -Idrivers/misc/
EXTRA_CFLAGS += -Iinclude/misc/

iva_ctl-objs=\
	iva_ctrl.o\
	iva_pmu.o\
	iva_mcu.o\
	iva_sh_mem.o\
	iva_ram_dump.o\
	iva_mbox.o\
	iva_ipc_queue.o\
	iva_mem.o\
	iva_mem_sync.o\
	iva_sysfs.o\
	iva_vdma.o
