#
# Makefile for MELFAS MMS400 Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438)	+= melfas_mms400.o melfas_mms400_mod.o melfas_mms400_test.o melfas_mms400_cmd.o melfas_mms438_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449)	+= melfas_mms400.o melfas_mms400_mod.o melfas_mms400_test.o melfas_mms400_cmd.o melfas_mms438_fw_update.o
