# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos8895-dreamlte_eur_open_05.dtb
dtb-y += exynos8895-dreamlte_eur_open_07.dtb
dtb-y += exynos8895-dreamlte_eur_open_08.dtb
dtb-y += exynos8895-dreamlte_eur_open_09.dtb
dtb-y += exynos8895-dreamlte_eur_open_10.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
