dtb-y += exynos9810-crownlte_eur_open_17.dtb
dtb-y += exynos9810-crownlte_eur_open_18.dtb
dtb-y += exynos9810-crownlte_eur_open_19.dtb
dtb-y += exynos9810-crownlte_eur_open_21.dtb
dtb-y += exynos9810-crownlte_eur_open_23.dtb
dtb-y += exynos9810-crownlte_eur_open_24.dtb
dtb-y += exynos9810-crownlte_eur_open_25.dtb
dtb-y += exynos9810-crownlte_eur_open_26.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
