#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation, and any use by you of this program is subject to the terms of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained from Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

ifeq ($(CONFIG_MALI_TMIX),y)
	ifeq ($(CONFIG_MALI_TMIX_R5P0),y)
		obj-y += tMIx/r5p0/
	endif
endif
ifeq ($(CONFIG_MALI_THEX),y)
	ifeq ($(CONFIG_MALI_THEX_R5P0),y)
		obj-y += tHEx/r5p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R7P0),y)
		obj-y += tHEx/r7p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R8P0),y)
		obj-y += tHEx/r8p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R9P0),y)
		obj-y += tHEx/r9p0/
	endif
endif
